<?php

use Illuminate\Database\Seeder;
use Illuminate\Support\Facades\DB;
use Carbon\Carbon;

class CountrySeeder extends Seeder
{
    /**
     * Run the database seeds.
     *
     * @return void
     */
    public function run()
    {
        DB::table('countries')->delete();
        $countries = [
            ['id' => 1, 'country_status' => true,'sort_name' => 'AF', 'title' => "Afghanistan", 'phone_code' => 93],
            ['id' => 2, 'country_status' => true,'sort_name' => 'AL', 'title' => "Albania", 'phone_code' => 355],
            ['id' => 3, 'country_status' => true,'sort_name' => 'DZ', 'title' => "Algeria", 'phone_code' => 213],
            ['id' => 4, 'country_status' => true,'sort_name' => 'AS', 'title' => "American Samoa", 'phone_code' => 1684],
            ['id' => 5, 'country_status' => true,'sort_name' => 'AD', 'title' => "Andorra", 'phone_code' => 376],
            ['id' => 6, 'country_status' => true,'sort_name' => 'AO', 'title' => "Angola", 'phone_code' => 244],
            ['id' => 7, 'country_status' => true,'sort_name' => 'AI', 'title' => "Anguilla", 'phone_code' => 1264],
            ['id' => 8, 'country_status' => true,'sort_name' => 'AQ', 'title' => "Antarctica", 'phone_code' => 0],
            ['id' => 9, 'country_status' => true,'sort_name' => 'AG', 'title' => "Antigua And Barbuda", 'phone_code' => 1268],
            ['id' => 10, 'country_status' => true,'sort_name' => 'AR', 'title' => "Argentina", 'phone_code' => 54],
            ['id' => 11, 'country_status' => true,'sort_name' => 'AM', 'title' => "Armenia", 'phone_code' => 374],
            ['id' => 12, 'country_status' => true,'sort_name' => 'AW', 'title' => "Aruba", 'phone_code' => 297],
            ['id' => 13, 'country_status' => true,'sort_name' => 'AU', 'title' => "Australia", 'phone_code' => 61],
            ['id' => 14, 'country_status' => true,'sort_name' => 'AT', 'title' => "Austria", 'phone_code' => 43],
            ['id' => 15, 'country_status' => true,'sort_name' => 'AZ', 'title' => "Azerbaijan", 'phone_code' => 994],
            ['id' => 16, 'country_status' => true,'sort_name' => 'BS', 'title' => "Bahamas The", 'phone_code' => 1242],
            ['id' => 17, 'country_status' => true,'sort_name' => 'BH', 'title' => "Bahrain", 'phone_code' => 973],
            ['id' => 18, 'country_status' => true,'sort_name' => 'BD', 'title' => "Bangladesh", 'phone_code' => 880],
            ['id' => 19, 'country_status' => true,'sort_name' => 'BB', 'title' => "Barbados", 'phone_code' => 1246],
            ['id' => 20, 'country_status' => true,'sort_name' => 'BY', 'title' => "Belarus", 'phone_code' => 375],
            ['id' => 21, 'country_status' => true,'sort_name' => 'BE', 'title' => "Belgium", 'phone_code' => 32],
            ['id' => 22, 'country_status' => true,'sort_name' => 'BZ', 'title' => "Belize", 'phone_code' => 501],
            ['id' => 23, 'country_status' => true,'sort_name' => 'BJ', 'title' => "Benin", 'phone_code' => 229],
            ['id' => 24, 'country_status' => true,'sort_name' => 'BM', 'title' => "Bermuda", 'phone_code' => 1441],
            ['id' => 25, 'country_status' => true,'sort_name' => 'BT', 'title' => "Bhutan", 'phone_code' => 975],
            ['id' => 26, 'country_status' => true,'sort_name' => 'BO', 'title' => "Bolivia", 'phone_code' => 591],
            ['id' => 27, 'country_status' => true,'sort_name' => 'BA', 'title' => "Bosnia and Herzegovina", 'phone_code' => 387],
            ['id' => 28, 'country_status' => true,'sort_name' => 'BW', 'title' => "Botswana", 'phone_code' => 267],
            ['id' => 29, 'country_status' => true,'sort_name' => 'BV', 'title' => "Bouvet Island", 'phone_code' => 0],
            ['id' => 30, 'country_status' => true,'sort_name' => 'BR', 'title' => "Brazil", 'phone_code' => 55],
            ['id' => 31, 'country_status' => true,'sort_name' => 'IO', 'title' => "British Indian Ocean Territory", 'phone_code' => 246],
            ['id' => 32, 'country_status' => true,'sort_name' => 'BN', 'title' => "Brunei", 'phone_code' => 673],
            ['id' => 33, 'country_status' => true,'sort_name' => 'BG', 'title' => "Bulgaria", 'phone_code' => 359],
            ['id' => 34, 'country_status' => true,'sort_name' => 'BF', 'title' => "Burkina Faso", 'phone_code' => 226],
            ['id' => 35, 'country_status' => true,'sort_name' => 'BI', 'title' => "Burundi", 'phone_code' => 257],
            ['id' => 36, 'country_status' => true,'sort_name' => 'KH', 'title' => "Cambodia", 'phone_code' => 855],
            ['id' => 37, 'country_status' => true,'sort_name' => 'CM', 'title' => "Cameroon", 'phone_code' => 237],
            ['id' => 38, 'country_status' => true,'sort_name' => 'CA', 'title' => "Canada", 'phone_code' => 1],
            ['id' => 39, 'country_status' => true,'sort_name' => 'CV', 'title' => "Cape Verde", 'phone_code' => 238],
            ['id' => 40, 'country_status' => true,'sort_name' => 'KY', 'title' => "Cayman Islands", 'phone_code' => 1345],
            ['id' => 41, 'country_status' => true,'sort_name' => 'CF', 'title' => "Central African Republic", 'phone_code' => 236],
            ['id' => 42, 'country_status' => true,'sort_name' => 'TD', 'title' => "Chad", 'phone_code' => 235],
            ['id' => 43, 'country_status' => true,'sort_name' => 'CL', 'title' => "Chile", 'phone_code' => 56],
            ['id' => 44, 'country_status' => true,'sort_name' => 'CN', 'title' => "China", 'phone_code' => 86],
            ['id' => 45, 'country_status' => true,'sort_name' => 'CX', 'title' => "Christmas Island", 'phone_code' => 61],
            ['id' => 46, 'country_status' => true,'sort_name' => 'CC', 'title' => "Cocos (Keeling) Islands", 'phone_code' => 672],
            ['id' => 47, 'country_status' => true,'sort_name' => 'CO', 'title' => "Colombia", 'phone_code' => 57],
            ['id' => 48, 'country_status' => true,'sort_name' => 'KM', 'title' => "Comoros", 'phone_code' => 269],
            ['id' => 49, 'country_status' => true,'sort_name' => 'CG', 'title' => "Congo", 'phone_code' => 242],
            ['id' => 50, 'country_status' => true,'sort_name' => 'CD', 'title' => "Congo The Democratic Republic Of The", 'phone_code' => 242],
            ['id' => 51, 'country_status' => true,'sort_name' => 'CK', 'title' => "Cook Islands", 'phone_code' => 682],
            ['id' => 52, 'country_status' => true,'sort_name' => 'CR', 'title' => "Costa Rica", 'phone_code' => 506],
            ['id' => 53, 'country_status' => true,'sort_name' => 'CI', 'title' => "Cote D Ivoire (Ivory Coast)", 'phone_code' => 225],
            ['id' => 54, 'country_status' => true,'sort_name' => 'HR', 'title' => "Croatia (Hrvatska)", 'phone_code' => 385],
            ['id' => 55, 'country_status' => true,'sort_name' => 'CU', 'title' => "Cuba", 'phone_code' => 53],
            ['id' => 56, 'country_status' => true,'sort_name' => 'CY', 'title' => "Cyprus", 'phone_code' => 357],
            ['id' => 57, 'country_status' => true,'sort_name' => 'CZ', 'title' => "Czech Republic", 'phone_code' => 420],
            ['id' => 58, 'country_status' => true,'sort_name' => 'DK', 'title' => "Denmark", 'phone_code' => 45],
            ['id' => 59, 'country_status' => true,'sort_name' => 'DJ', 'title' => "Djibouti", 'phone_code' => 253],
            ['id' => 60, 'country_status' => true,'sort_name' => 'DM', 'title' => "Dominica", 'phone_code' => 1767],
            ['id' => 61, 'country_status' => true,'sort_name' => 'DO', 'title' => "Dominican Republic", 'phone_code' => 1809],
            ['id' => 62, 'country_status' => true,'sort_name' => 'TP', 'title' => "East Timor", 'phone_code' => 670],
            ['id' => 63, 'country_status' => true,'sort_name' => 'EC', 'title' => "Ecuador", 'phone_code' => 593],
            ['id' => 64, 'country_status' => true,'sort_name' => 'EG', 'title' => "Egypt", 'phone_code' => 20],
            ['id' => 65, 'country_status' => true,'sort_name' => 'SV', 'title' => "El Salvador", 'phone_code' => 503],
            ['id' => 66, 'country_status' => true,'sort_name' => 'GQ', 'title' => "Equatorial Guinea", 'phone_code' => 240],
            ['id' => 67, 'country_status' => true,'sort_name' => 'ER', 'title' => "Eritrea", 'phone_code' => 291],
            ['id' => 68, 'country_status' => true,'sort_name' => 'EE', 'title' => "Estonia", 'phone_code' => 372],
            ['id' => 69, 'country_status' => true,'sort_name' => 'ET', 'title' => "Ethiopia", 'phone_code' => 251],
            ['id' => 70, 'country_status' => true,'sort_name' => 'XA', 'title' => "External Territories of Australia", 'phone_code' => 61],
            ['id' => 71, 'country_status' => true,'sort_name' => 'FK', 'title' => "Falkland Islands", 'phone_code' => 500],
            ['id' => 72, 'country_status' => true,'sort_name' => 'FO', 'title' => "Faroe Islands", 'phone_code' => 298],
            ['id' => 73, 'country_status' => true,'sort_name' => 'FJ', 'title' => "Fiji Islands", 'phone_code' => 679],
            ['id' => 74, 'country_status' => true,'sort_name' => 'FI', 'title' => "Finland", 'phone_code' => 358],
            ['id' => 75, 'country_status' => true,'sort_name' => 'FR', 'title' => "France", 'phone_code' => 33],
            ['id' => 76, 'country_status' => true,'sort_name' => 'GF', 'title' => "French Guiana", 'phone_code' => 594],
            ['id' => 77, 'country_status' => true,'sort_name' => 'PF', 'title' => "French Polynesia", 'phone_code' => 689],
            ['id' => 78, 'country_status' => true,'sort_name' => 'TF', 'title' => "French Southern Territories", 'phone_code' => 0],
            ['id' => 79, 'country_status' => true,'sort_name' => 'GA', 'title' => "Gabon", 'phone_code' => 241],
            ['id' => 80, 'country_status' => true,'sort_name' => 'GM', 'title' => "Gambia The", 'phone_code' => 220],
            ['id' => 81, 'country_status' => true,'sort_name' => 'GE', 'title' => "Georgia", 'phone_code' => 995],
            ['id' => 82, 'country_status' => true,'sort_name' => 'DE', 'title' => "Germany", 'phone_code' => 49],
            ['id' => 83, 'country_status' => true,'sort_name' => 'GH', 'title' => "Ghana", 'phone_code' => 233],
            ['id' => 84, 'country_status' => true,'sort_name' => 'GI', 'title' => "Gibraltar", 'phone_code' => 350],
            ['id' => 85, 'country_status' => true,'sort_name' => 'GR', 'title' => "Greece", 'phone_code' => 30],
            ['id' => 86, 'country_status' => true,'sort_name' => 'GL', 'title' => "Greenland", 'phone_code' => 299],
            ['id' => 87, 'country_status' => true,'sort_name' => 'GD', 'title' => "Grenada", 'phone_code' => 1473],
            ['id' => 88, 'country_status' => true,'sort_name' => 'GP', 'title' => "Guadeloupe", 'phone_code' => 590],
            ['id' => 89, 'country_status' => true,'sort_name' => 'GU', 'title' => "Guam", 'phone_code' => 1671],
            ['id' => 90, 'country_status' => true,'sort_name' => 'GT', 'title' => "Guatemala", 'phone_code' => 502],
            ['id' => 91, 'country_status' => true,'sort_name' => 'XU', 'title' => "Guernsey and Alderney", 'phone_code' => 44],
            ['id' => 92, 'country_status' => true,'sort_name' => 'GN', 'title' => "Guinea", 'phone_code' => 224],
            ['id' => 93, 'country_status' => true,'sort_name' => 'GW', 'title' => "Guinea-Bissau", 'phone_code' => 245],
            ['id' => 94, 'country_status' => true,'sort_name' => 'GY', 'title' => "Guyana", 'phone_code' => 592],
            ['id' => 95, 'country_status' => true,'sort_name' => 'HT', 'title' => "Haiti", 'phone_code' => 509],
            ['id' => 96, 'country_status' => true,'sort_name' => 'HM', 'title' => "Heard and McDonald Islands", 'phone_code' => 0],
            ['id' => 97, 'country_status' => true,'sort_name' => 'HN', 'title' => "Honduras", 'phone_code' => 504],
            ['id' => 98, 'country_status' => true,'sort_name' => 'HK', 'title' => "Hong Kong S.A.R.", 'phone_code' => 852],
            ['id' => 99, 'country_status' => true,'sort_name' => 'HU', 'title' => "Hungary", 'phone_code' => 36],
            ['id' => 100, 'country_status' => true,'sort_name' => 'IS', 'title' => "Iceland", 'phone_code' => 354],
            ['id' => 101, 'country_status' => true,'sort_name' => 'IN', 'title' => "India", 'phone_code' => 91],
            ['id' => 102, 'country_status' => true,'sort_name' => 'ID', 'title' => "Indonesia", 'phone_code' => 62],
            ['id' => 103, 'country_status' => true,'sort_name' => 'IR', 'title' => "Iran", 'phone_code' => 98],
            ['id' => 104, 'country_status' => true,'sort_name' => 'IQ', 'title' => "Iraq", 'phone_code' => 964],
            ['id' => 105, 'country_status' => true,'sort_name' => 'IE', 'title' => "Ireland", 'phone_code' => 353],
            ['id' => 106, 'country_status' => true,'sort_name' => 'IL', 'title' => "Israel", 'phone_code' => 972],
            ['id' => 107, 'country_status' => true,'sort_name' => 'IT', 'title' => "Italy", 'phone_code' => 39],
            ['id' => 108, 'country_status' => true,'sort_name' => 'JM', 'title' => "Jamaica", 'phone_code' => 1876],
            ['id' => 109, 'country_status' => true,'sort_name' => 'JP', 'title' => "Japan", 'phone_code' => 81],
            ['id' => 110, 'country_status' => true,'sort_name' => 'XJ', 'title' => "Jersey", 'phone_code' => 44],
            ['id' => 111, 'country_status' => true,'sort_name' => 'JO', 'title' => "Jordan", 'phone_code' => 962],
            ['id' => 112, 'country_status' => true,'sort_name' => 'KZ', 'title' => "Kazakhstan", 'phone_code' => 7],
            ['id' => 113, 'country_status' => true,'sort_name' => 'KE', 'title' => "Kenya", 'phone_code' => 254],
            ['id' => 114, 'country_status' => true,'sort_name' => 'KI', 'title' => "Kiribati", 'phone_code' => 686],
            ['id' => 115, 'country_status' => true,'sort_name' => 'KP', 'title' => "Korea North", 'phone_code' => 850],
            ['id' => 116, 'country_status' => true,'sort_name' => 'KR', 'title' => "Korea South", 'phone_code' => 82],
            ['id' => 117, 'country_status' => true,'sort_name' => 'KW', 'title' => "Kuwait", 'phone_code' => 965],
            ['id' => 118, 'country_status' => true,'sort_name' => 'KG', 'title' => "Kyrgyzstan", 'phone_code' => 996],
            ['id' => 119, 'country_status' => true,'sort_name' => 'LA', 'title' => "Laos", 'phone_code' => 856],
            ['id' => 120, 'country_status' => true,'sort_name' => 'LV', 'title' => "Latvia", 'phone_code' => 371],
            ['id' => 121, 'country_status' => true,'sort_name' => 'LB', 'title' => "Lebanon", 'phone_code' => 961],
            ['id' => 122, 'country_status' => true,'sort_name' => 'LS', 'title' => "Lesotho", 'phone_code' => 266],
            ['id' => 123, 'country_status' => true,'sort_name' => 'LR', 'title' => "Liberia", 'phone_code' => 231],
            ['id' => 124, 'country_status' => true,'sort_name' => 'LY', 'title' => "Libya", 'phone_code' => 218],
            ['id' => 125, 'country_status' => true,'sort_name' => 'LI', 'title' => "Liechtenstein", 'phone_code' => 423],
            ['id' => 126, 'country_status' => true,'sort_name' => 'LT', 'title' => "Lithuania", 'phone_code' => 370],
            ['id' => 127, 'country_status' => true,'sort_name' => 'LU', 'title' => "Luxembourg", 'phone_code' => 352],
            ['id' => 128, 'country_status' => true,'sort_name' => 'MO', 'title' => "Macau S.A.R.", 'phone_code' => 853],
            ['id' => 129, 'country_status' => true,'sort_name' => 'MK', 'title' => "Macedonia", 'phone_code' => 389],
            ['id' => 130, 'country_status' => true,'sort_name' => 'MG', 'title' => "Madagascar", 'phone_code' => 261],
            ['id' => 131, 'country_status' => true,'sort_name' => 'MW', 'title' => "Malawi", 'phone_code' => 265],
            ['id' => 132, 'country_status' => true,'sort_name' => 'MY', 'title' => "Malaysia", 'phone_code' => 60],
            ['id' => 133, 'country_status' => true,'sort_name' => 'MV', 'title' => "Maldives", 'phone_code' => 960],
            ['id' => 134, 'country_status' => true,'sort_name' => 'ML', 'title' => "Mali", 'phone_code' => 223],
            ['id' => 135, 'country_status' => true,'sort_name' => 'MT', 'title' => "Malta", 'phone_code' => 356],
            ['id' => 136, 'country_status' => true,'sort_name' => 'XM', 'title' => "Man (Isle of)", 'phone_code' => 44],
            ['id' => 137, 'country_status' => true,'sort_name' => 'MH', 'title' => "Marshall Islands", 'phone_code' => 692],
            ['id' => 138, 'country_status' => true,'sort_name' => 'MQ', 'title' => "Martinique", 'phone_code' => 596],
            ['id' => 139, 'country_status' => true,'sort_name' => 'MR', 'title' => "Mauritania", 'phone_code' => 222],
            ['id' => 140, 'country_status' => true,'sort_name' => 'MU', 'title' => "Mauritius", 'phone_code' => 230],
            ['id' => 141, 'country_status' => true,'sort_name' => 'YT', 'title' => "Mayotte", 'phone_code' => 269],
            ['id' => 142, 'country_status' => true,'sort_name' => 'MX', 'title' => "Mexico", 'phone_code' => 52],
            ['id' => 143, 'country_status' => true,'sort_name' => 'FM', 'title' => "Micronesia", 'phone_code' => 691],
            ['id' => 144, 'country_status' => true,'sort_name' => 'MD', 'title' => "Moldova", 'phone_code' => 373],
            ['id' => 145, 'country_status' => true,'sort_name' => 'MC', 'title' => "Monaco", 'phone_code' => 377],
            ['id' => 146, 'country_status' => true,'sort_name' => 'MN', 'title' => "Mongolia", 'phone_code' => 976],
            ['id' => 147, 'country_status' => true,'sort_name' => 'MS', 'title' => "Montserrat", 'phone_code' => 1664],
            ['id' => 148, 'country_status' => true,'sort_name' => 'MA', 'title' => "Morocco", 'phone_code' => 212],
            ['id' => 149, 'country_status' => true,'sort_name' => 'MZ', 'title' => "Mozambique", 'phone_code' => 258],
            ['id' => 150, 'country_status' => true,'sort_name' => 'MM', 'title' => "Myanmar", 'phone_code' => 95],
            ['id' => 151, 'country_status' => true,'sort_name' => 'NA', 'title' => "Namibia", 'phone_code' => 264],
            ['id' => 152, 'country_status' => true,'sort_name' => 'NR', 'title' => "Nauru", 'phone_code' => 674],
            ['id' => 153, 'country_status' => true,'sort_name' => 'NP', 'title' => "Nepal", 'phone_code' => 977],
            ['id' => 154, 'country_status' => true,'sort_name' => 'AN', 'title' => "Netherlands Antilles", 'phone_code' => 599],
            ['id' => 155, 'country_status' => true,'sort_name' => 'NL', 'title' => "Netherlands The", 'phone_code' => 31],
            ['id' => 156, 'country_status' => true,'sort_name' => 'NC', 'title' => "New Caledonia", 'phone_code' => 687],
            ['id' => 157, 'country_status' => true,'sort_name' => 'NZ', 'title' => "New Zealand", 'phone_code' => 64],
            ['id' => 158, 'country_status' => true,'sort_name' => 'NI', 'title' => "Nicaragua", 'phone_code' => 505],
            ['id' => 159, 'country_status' => true,'sort_name' => 'NE', 'title' => "Niger", 'phone_code' => 227],
            ['id' => 160, 'country_status' => true,'sort_name' => 'NG', 'title' => "Nigeria", 'phone_code' => 234],
            ['id' => 161, 'country_status' => true,'sort_name' => 'NU', 'title' => "Niue", 'phone_code' => 683],
            ['id' => 162, 'country_status' => true,'sort_name' => 'NF', 'title' => "Norfolk Island", 'phone_code' => 672],
            ['id' => 163, 'country_status' => true,'sort_name' => 'MP', 'title' => "Northern Mariana Islands", 'phone_code' => 1670],
            ['id' => 164, 'country_status' => true,'sort_name' => 'NO', 'title' => "Norway", 'phone_code' => 47],
            ['id' => 165, 'country_status' => true,'sort_name' => 'OM', 'title' => "Oman", 'phone_code' => 968],
            ['id' => 166, 'country_status' => true,'sort_name' => 'PK', 'title' => "Pakistan", 'phone_code' => 92],
            ['id' => 167, 'country_status' => true,'sort_name' => 'PW', 'title' => "Palau", 'phone_code' => 680],
            ['id' => 168, 'country_status' => true,'sort_name' => 'PS', 'title' => "Palestinian Territory Occupied", 'phone_code' => 970],
            ['id' => 169, 'country_status' => true,'sort_name' => 'PA', 'title' => "Panama", 'phone_code' => 507],
            ['id' => 170, 'country_status' => true,'sort_name' => 'PG', 'title' => "Papua new Guinea", 'phone_code' => 675],
            ['id' => 171, 'country_status' => true,'sort_name' => 'PY', 'title' => "Paraguay", 'phone_code' => 595],
            ['id' => 172, 'country_status' => true,'sort_name' => 'PE', 'title' => "Peru", 'phone_code' => 51],
            ['id' => 173, 'country_status' => true,'sort_name' => 'PH', 'title' => "Philippines", 'phone_code' => 63],
            ['id' => 174, 'country_status' => true,'sort_name' => 'PN', 'title' => "Pitcairn Island", 'phone_code' => 0],
            ['id' => 175, 'country_status' => true,'sort_name' => 'PL', 'title' => "Poland", 'phone_code' => 48],
            ['id' => 176, 'country_status' => true,'sort_name' => 'PT', 'title' => "Portugal", 'phone_code' => 351],
            ['id' => 177, 'country_status' => true,'sort_name' => 'PR', 'title' => "Puerto Rico", 'phone_code' => 1787],
            ['id' => 178, 'country_status' => true,'sort_name' => 'QA', 'title' => "Qatar", 'phone_code' => 974],
            ['id' => 179, 'country_status' => true,'sort_name' => 'RE', 'title' => "Reunion", 'phone_code' => 262],
            ['id' => 180, 'country_status' => true,'sort_name' => 'RO', 'title' => "Romania", 'phone_code' => 40],
            ['id' => 181, 'country_status' => true,'sort_name' => 'RU', 'title' => "Russia", 'phone_code' => 70],
            ['id' => 182, 'country_status' => true,'sort_name' => 'RW', 'title' => "Rwanda", 'phone_code' => 250],
            ['id' => 183, 'country_status' => true,'sort_name' => 'SH', 'title' => "Saint Helena", 'phone_code' => 290],
            ['id' => 184, 'country_status' => true,'sort_name' => 'KN', 'title' => "Saint Kitts And Nevis", 'phone_code' => 1869],
            ['id' => 185, 'country_status' => true,'sort_name' => 'LC', 'title' => "Saint Lucia", 'phone_code' => 1758],
            ['id' => 186, 'country_status' => true,'sort_name' => 'PM', 'title' => "Saint Pierre and Miquelon", 'phone_code' => 508],
            ['id' => 187, 'country_status' => true,'sort_name' => 'VC', 'title' => "Saint Vincent And The Grenadines", 'phone_code' => 1784],
            ['id' => 188, 'country_status' => true,'sort_name' => 'WS', 'title' => "Samoa", 'phone_code' => 684],
            ['id' => 189, 'country_status' => true,'sort_name' => 'SM', 'title' => "San Marino", 'phone_code' => 378],
            ['id' => 190, 'country_status' => true,'sort_name' => 'ST', 'title' => "Sao Tome and Principe", 'phone_code' => 239],
            ['id' => 191, 'country_status' => true,'sort_name' => 'SA', 'title' => "Saudi Arabia", 'phone_code' => 966],
            ['id' => 192, 'country_status' => true,'sort_name' => 'SN', 'title' => "Senegal", 'phone_code' => 221],
            ['id' => 193, 'country_status' => true,'sort_name' => 'RS', 'title' => "Serbia", 'phone_code' => 381],
            ['id' => 194, 'country_status' => true,'sort_name' => 'SC', 'title' => "Seychelles", 'phone_code' => 248],
            ['id' => 195, 'country_status' => true,'sort_name' => 'SL', 'title' => "Sierra Leone", 'phone_code' => 232],
            ['id' => 196, 'country_status' => true,'sort_name' => 'SG', 'title' => "Singapore", 'phone_code' => 65],
            ['id' => 197, 'country_status' => true,'sort_name' => 'SK', 'title' => "Slovakia", 'phone_code' => 421],
            ['id' => 198, 'country_status' => true,'sort_name' => 'SI', 'title' => "Slovenia", 'phone_code' => 386],
            ['id' => 199, 'country_status' => true,'sort_name' => 'XG', 'title' => "Smaller Territories of the UK", 'phone_code' => 44],
            ['id' => 200, 'country_status' => true,'sort_name' => 'SB', 'title' => "Solomon Islands", 'phone_code' => 677],
            ['id' => 201, 'country_status' => true,'sort_name' => 'SO', 'title' => "Somalia", 'phone_code' => 252],
            ['id' => 202, 'country_status' => true,'sort_name' => 'ZA', 'title' => "South Africa", 'phone_code' => 27],
            ['id' => 203, 'country_status' => true,'sort_name' => 'GS', 'title' => "South Georgia", 'phone_code' => 0],
            ['id' => 204, 'country_status' => true,'sort_name' => 'SS', 'title' => "South Sudan", 'phone_code' => 211],
            ['id' => 205, 'country_status' => true,'sort_name' => 'ES', 'title' => "Spain", 'phone_code' => 34],
            ['id' => 206, 'country_status' => true,'sort_name' => 'LK', 'title' => "Sri Lanka", 'phone_code' => 94],
            ['id' => 207, 'country_status' => true,'sort_name' => 'SD', 'title' => "Sudan", 'phone_code' => 249],
            ['id' => 208, 'country_status' => true,'sort_name' => 'SR', 'title' => "Suriname", 'phone_code' => 597],
            ['id' => 209, 'country_status' => true,'sort_name' => 'SJ', 'title' => "Svalbard And Jan Mayen Islands", 'phone_code' => 47],
            ['id' => 210, 'country_status' => true,'sort_name' => 'SZ', 'title' => "Swaziland", 'phone_code' => 268],
            ['id' => 211, 'country_status' => true,'sort_name' => 'SE', 'title' => "Sweden", 'phone_code' => 46],
            ['id' => 212, 'country_status' => true,'sort_name' => 'CH', 'title' => "Switzerland", 'phone_code' => 41],
            ['id' => 213, 'country_status' => true,'sort_name' => 'SY', 'title' => "Syria", 'phone_code' => 963],
            ['id' => 214, 'country_status' => true,'sort_name' => 'TW', 'title' => "Taiwan", 'phone_code' => 886],
            ['id' => 215, 'country_status' => true,'sort_name' => 'TJ', 'title' => "Tajikistan", 'phone_code' => 992],
            ['id' => 216, 'country_status' => true,'sort_name' => 'TZ', 'title' => "Tanzania", 'phone_code' => 255],
            ['id' => 217, 'country_status' => true,'sort_name' => 'TH', 'title' => "Thailand", 'phone_code' => 66],
            ['id' => 218, 'country_status' => true,'sort_name' => 'TG', 'title' => "Togo", 'phone_code' => 228],
            ['id' => 219, 'country_status' => true,'sort_name' => 'TK', 'title' => "Tokelau", 'phone_code' => 690],
            ['id' => 220, 'country_status' => true,'sort_name' => 'TO', 'title' => "Tonga", 'phone_code' => 676],
            ['id' => 221, 'country_status' => true,'sort_name' => 'TT', 'title' => "Trinidad And Tobago", 'phone_code' => 1868],
            ['id' => 222, 'country_status' => true,'sort_name' => 'TN', 'title' => "Tunisia", 'phone_code' => 216],
            ['id' => 223, 'country_status' => true,'sort_name' => 'TR', 'title' => "Turkey", 'phone_code' => 90],
            ['id' => 224, 'country_status' => true,'sort_name' => 'TM', 'title' => "Turkmenistan", 'phone_code' => 7370],
            ['id' => 225, 'country_status' => true,'sort_name' => 'TC', 'title' => "Turks And Caicos Islands", 'phone_code' => 1649],
            ['id' => 226, 'country_status' => true,'sort_name' => 'TV', 'title' => "Tuvalu", 'phone_code' => 688],
            ['id' => 227, 'country_status' => true,'sort_name' => 'UG', 'title' => "Uganda", 'phone_code' => 256],
            ['id' => 228, 'country_status' => true,'sort_name' => 'UA', 'title' => "Ukraine", 'phone_code' => 380],
            ['id' => 229, 'country_status' => true,'sort_name' => 'AE', 'title' => "United Arab Emirates", 'phone_code' => 971],
            ['id' => 230, 'country_status' => true,'sort_name' => 'GB', 'title' => "United Kingdom", 'phone_code' => 44],
            ['id' => 231, 'country_status' => true,'sort_name' => 'US', 'title' => "United States", 'phone_code' => 1],
            ['id' => 232, 'country_status' => true,'sort_name' => 'UM', 'title' => "United States Minor Outlying Islands", 'phone_code' => 1],
            ['id' => 233, 'country_status' => true,'sort_name' => 'UY', 'title' => "Uruguay", 'phone_code' => 598],
            ['id' => 234, 'country_status' => true,'sort_name' => 'UZ', 'title' => "Uzbekistan", 'phone_code' => 998],
            ['id' => 235, 'country_status' => true,'sort_name' => 'VU', 'title' => "Vanuatu", 'phone_code' => 678],
            ['id' => 236, 'country_status' => true,'sort_name' => 'VA', 'title' => "Vatican City State (Holy See)", 'phone_code' => 39],
            ['id' => 237, 'country_status' => true,'sort_name' => 'VE', 'title' => "Venezuela", 'phone_code' => 58],
            ['id' => 238, 'country_status' => true,'sort_name' => 'VN', 'title' => "Vietnam", 'phone_code' => 84],
            ['id' => 239, 'country_status' => true,'sort_name' => 'VG', 'title' => "Virgin Islands (British)", 'phone_code' => 1284],
            ['id' => 240, 'country_status' => true,'sort_name' => 'VI', 'title' => "Virgin Islands (US)", 'phone_code' => 1340],
            ['id' => 241, 'country_status' => true,'sort_name' => 'WF', 'title' => "Wallis And Futuna Islands", 'phone_code' => 681],
            ['id' => 242, 'country_status' => true,'sort_name' => 'EH', 'title' => "Western Sahara", 'phone_code' => 212],
            ['id' => 243, 'country_status' => true,'sort_name' => 'YE', 'title' => "Yemen", 'phone_code' => 967],
            ['id' => 244, 'country_status' => true,'sort_name' => 'YU', 'title' => "Yugoslavia", 'phone_code' => 38],
            ['id' => 245, 'country_status' => true,'sort_name' => 'ZM', 'title' => "Zambia", 'phone_code' => 260],
            ['id' => 246, 'country_status' => true,'sort_name' => 'ZW', 'title' => "Zimbabwe", 'phone_code' => 263],
        ];
        $data = [];
        foreach ($countries as $country) {
            $country['created_at'] = Carbon::now();
            $country['updated_at'] = Carbon::now();
            $data[] = $country;
        }
        DB::table('countries')->insert($data);
    }
}
